### ISSUE TITLE
pdfjs-dist version 3.11.174 allows Javascript code to be injected through PDFs. 

### ISSUE THREAD

**Issue by derekGou** [Utkarsh212/react-pdftotext#6]
Really love this package, but react-pdftotext relies on react-pdf version 8.0.2, which itself relies on a vulnerable version of pdfjs-dist (needs to be upgraded to at least 4.2.67), which means react-pdf needs to be upgraded to 9.0.0 or 9.1.0.

**Comment by Utkarsh212** [comment]
@derekGou , thank you for bringing this to my attention. I addressed the issue by upgrading dependencies to a safer version in the latest release, [v1.3.3](https://www.npmjs.com/package/react-pdftotext)
